spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eaas
    username: root
    password:
mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: mybatis/mybatis-config.xml

